Add wmts
swisstopo/swissgeol-boreholes-suite pull request #1571
Opened 2024-10-03 15:21 UTC by MiraGeowerkstatt

Resolves #1503

2024-10-04 12:17 UTC, flenny submitted a review, later dismissed

2024-10-04 12:17 UTC, flenny commented on src/client/src/pages/settings/components/editorSettingList/mapSettings.jsx
> +          showAlert("Sorry, only Web Map Services (WMS) and " + "Web Map Tile Service (WMTS) are supported", "error");
Q: internationalization?
PP:
```suggestion
          showAlert("Sorry, only Web Map Services (WMS) and " + "Web Map Tile Services (WMTS) are supported", "error");
```

2024-10-04 12:17 UTC, flenny commented on src/client/src/pages/settings/components/editorSettingList/mapSettings.jsx
> +                  {state.wmts === null ? null : getWmtsList()}
PP:
```suggestion
                  {state.wms && getWmsList()}
                  {state.wmts && getWmtsList()}
```

2024-10-04 12:17 UTC, flenny commented on src/client/src/pages/settings/editorSettings.tsx
> +          showAlert("Only EPSG:2056 is supported", "error");
Q: internationalization?
PP: duplicated code.

2024-10-04 12:17 UTC, flenny commented on src/client/src/pages/settings/editorSettings.tsx
> +        showAlert("Only EPSG:2056 is supported", "error");
Q: internationalization?

2024-10-08 06:43 UTC, danjov approved these changes

2024-10-08 06:43 UTC, danjov requested changes
REQ: Changelog-Eintrag

2024-10-08 08:27 UTC, danjov approved these changes

2024-10-08 10:39 UTC, danjov submitted a review, later dismissed

2024-10-09 11:15 UTC, danjov approved these changes

2024-10-09 11:28 UTC, merged