Adapt borehole general segment
swisstopo/swissgeol-boreholes-suite pull request #1647
Opened 2024-11-07 15:53 UTC by MiraGeowerkstatt

[#1395](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1395)
Implementiert die neue Speicherlogik.
Es fehlt noch das Restyling der Tabs (General, Sections, Geometry)

2024-11-11 16:17 UTC, danjov requested changes

2024-11-11 16:17 UTC, danjov commented on src/client/src/pages/detail/form/borehole/boreholeForm.tsx
> +  //
REQ: Leeren Kommentar löschen.

2024-11-11 16:17 UTC, danjov commented on src/client/src/pages/detail/form/borehole/boreholeForm.tsx
> +        return depth;
PP: 
```suggestion
        return roundTvdValue(depth);
```

2024-11-12 06:00 UTC, Lehats approved these changes

2024-11-18 10:05 UTC, danjov approved these changes

2024-11-18 10:06 UTC, merged