Add permissions check before retrieving borehole file info
swisstopo/swissgeol-boreholes-suite pull request #1661
Opened 2024-11-18 12:50 UTC by MiraGeowerkstatt

#1546

2024-11-18 13:02 UTC, danjov requested changes

2024-11-18 13:54 UTC, Lehats commented on src/api/IBoreholeLockService.cs
>      /// <exception cref="UnauthorizedAccessException">Current user is not allowed to create the given <see cref="Stratigraphy"/>.</exception>
Q: Ist Stratigraphy hier korrekt?

2024-11-18 14:30 UTC, danjov requested changes

2024-11-18 14:30 UTC, danjov commented on src/api/BoreholeLockService.cs
> +        {
REQ: Einrückung korrigieren

2024-11-18 14:40 UTC, MiraGeowerkstatt commented on src/api/IBoreholeLockService.cs
>      /// <exception cref="UnauthorizedAccessException">Current user is not allowed to create the given <see cref="Stratigraphy"/>.</exception>
Hab ich mich auch gefragt :D @danjov ist das noch ein Überbleibsel von als der Service nur für die Stratigraphy benutzt wurde?

2024-11-18 14:57 UTC, danjov commented on src/api/IBoreholeLockService.cs
>      /// <exception cref="UnauthorizedAccessException">Current user is not allowed to create the given <see cref="Stratigraphy"/>.</exception>
@MiraGeowerkstatt Vermutlich schon 🙈 Bitte anpassen, Danke :)

2024-11-18 15:07 UTC, MiraGeowerkstatt commented on src/api/IBoreholeLockService.cs
>      /// <exception cref="UnauthorizedAccessException">Current user is not allowed to create the given <see cref="Stratigraphy"/>.</exception>
Habs komplett entfernt, da die auch nirgends geworfen wird

2024-11-18 16:52 UTC, danjov approved these changes

2024-11-19 07:14 UTC, Lehats approved these changes

2024-11-19 09:14 UTC, merged