Getall endpoint api
swisstopo/swissgeol-boreholes-suite pull request #1715
Opened 2024-12-02 05:16 UTC by Lehats

Resolves #1676

2024-12-02 07:55 UTC, MiraGeowerkstatt commented on src/api/Controllers/BoreholeController.cs
> +        pageSize = pageSize > MaxPageSize ? MaxPageSize : pageSize;
PP: Math.Min(pageSize, MaxPageSize);

2024-12-02 07:55 UTC, MiraGeowerkstatt commented on src/api/Controllers/BoreholeController.cs
> +    private const int MaxPageSize = 100;
Q: Ist der Grund das zu limitieren Performance?

2024-12-02 07:55 UTC, MiraGeowerkstatt commented on src/api/Controllers/BoreholeController.cs
> +        var paginatedResponse = new PaginatedResponse<Borehole>(items, totalCount, pageNumber, pageSize, MaxPageSize);
Q: Was ist der Grund pageNumber, pageSize und MaxPageSize zu returnen?

2024-12-02 07:55 UTC, MiraGeowerkstatt commented on tests/api/Controllers/BoreholeControllerTest.cs
> +
Q: Brauchtes noch ein Testcase mit dem Get ohne parameter?

2024-12-02 08:43 UTC, danjov requested changes

2024-12-02 08:43 UTC, danjov commented on CHANGELOG.md
> +- Added borehole get all endpoint.
PP: `Added new API endpoint to retrieve all boreholes.`

2024-12-02 08:43 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +    private const int MaxPageSize = 100;
PP: Antwort/Intention gleich als Kommentar im Code hinzufügen.

2024-12-02 08:43 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +        var paginatedResponse = new PaginatedResponse<Borehole>(items, totalCount, pageNumber, pageSize, MaxPageSize);
PP: Zwischen diesen drei Variablendefinitionen braucht es keinen Whitespace, das zieht den Code ziemlich in die Länge. Das Gleiche ist für `skip` und `query` oben auch zu prüfen.

2024-12-02 08:43 UTC, danjov commented on src/api/Controllers/PaginatedResponse.cs
> +public class PaginatedResponse<T>
Q/REQ: Muss dieser Typ generisch sein? Aktuell wird es nur für Boreholes verwendet und in naher Zukunft vermutlich für nichts anderes. Falls dem so ist, würde ich den Typen zu z.B. `PaginatedBoreholesResponse` oder `GetAllBoreholesResponse` umbenennen und den generischen Parameter weglassen.  
Zusätzlich zu prüfen: `record`-Type anstatt `class` verwenden. Mit `record` spart man sich den Konstruktor unten.

2024-12-03 05:12 UTC, Lehats commented on src/api/Controllers/BoreholeController.cs
> +    private const int MaxPageSize = 100;
@MiraGeowerkstatt Genau. Jedoch auch das Dilemma mit der max URL length wenn die  `ids` Liste gross wird. Habe es daher auch noch gerade als MaxLength-Attribut für den `ids`-Parameter definiert.

2024-12-03 05:26 UTC, Lehats commented on src/api/Controllers/BoreholeController.cs
> +        var paginatedResponse = new PaginatedResponse<Borehole>(items, totalCount, pageNumber, pageSize, MaxPageSize);
Müsste man nicht. Ich finde es jedoch praktisch für den Konsumenten. Ich finde es erhöht die Transparenz. Was meint ihr?

2024-12-03 05:30 UTC, Lehats commented on tests/api/Controllers/BoreholeControllerTest.cs
> +
Ja stimmt. Ist etwas überflüssig.

2024-12-03 06:51 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +        var paginatedResponse = new PaginatedResponse<Borehole>(items, totalCount, pageNumber, pageSize, MaxPageSize);
Braucht es das nicht für die Tabelle auf dem Client? Dort haben wir eine auch ein Paging, welches mit diesem hier _gesynced_ sein sollte.

2024-12-03 07:11 UTC, Lehats commented on src/api/Controllers/BoreholeController.cs
> +        var paginatedResponse = new PaginatedResponse<Borehole>(items, totalCount, pageNumber, pageSize, MaxPageSize);
pageNumber, pageSize sind eigentlich schon essenziell. MaxPageSize finde ich persönlich auch noch gut. Aber ja das wäre nicht unbedingt nötig.

2024-12-03 11:19 UTC, danjov approved these changes

2024-12-03 16:30 UTC, merged