Update json export
swisstopo/swissgeol-boreholes-suite pull request #1720
Opened 2024-12-04 09:49 UTC by Lehats

Resolves #1719

2024-12-04 09:57 UTC, danjov submitted a review, later dismissed

2024-12-04 10:10 UTC, MiraGeowerkstatt requested changes

2024-12-04 10:10 UTC, MiraGeowerkstatt commented on src/client/src/pages/overview/boreholeTable/bottomBarContainer.tsx
> +    const selectedIds = selectionModel.map(id => Number(id));
REQ getAllBoreholes returned maximal 100 Boreholes, wenn das SelectionModel aber mehr als 100 Ids enthält braucht es noch ein Feedback an den User. Ich denke aus UX Sicht wäre ein Alert mit 2 Optionen vor dem Export am besten:
 sowas in die Richtung:
 "Es können maximal 100 Bohrungen exportiert werden. Wollen Sie fortfahren?" 
 Button 1:  100 erste Bohrungen exportieren
 Button 2: Abbrechen

2024-12-04 10:10 UTC, MiraGeowerkstatt commented on src/client/src/pages/overview/boreholeTable/bottomBarContainer.tsx
> +    const selectedIds = selectionModel.map(id => Number(id));
Q: brauchts das mapping selectionModel.map(id => Number(id));? Ich glaube selectionModel ist im grund schon ein number[ ]. Wenn typescript meckert könnte man  vielleicht auch die Signatur von gelAllBoreholes anpassen ? zu

export const getAllBoreholes = async (ids: number[] | GridRowSelectionMode, pageNumber: number, pageSize: number) => {

2024-12-05 09:34 UTC, MiraGeowerkstatt commented on src/client/src/pages/overview/boreholeTable/bottomBarContainer.tsx
> +    const selectedIds = selectionModel.map(id => Number(id));
Nach Absprache werde ich das im CSV Export Umsetzen

2024-12-05 09:34 UTC, MiraGeowerkstatt approved these changes

2024-12-05 09:37 UTC, danjov approved these changes

2024-12-05 09:48 UTC, merged