Remove import
swisstopo/swissgeol-boreholes-suite pull request #1758
Opened 2024-12-12 21:40 UTC by MiraGeowerkstatt

Vorbereitung für #1637 Umbau Csv-Import

2024-12-13 07:15 UTC, danjov requested changes
REQ: Eintrag ins Changelog hinzufügen.

2024-12-16 05:51 UTC, Lehats approved these changes

2024-12-16 12:45 UTC, danjov submitted a review, later dismissed

2024-12-16 14:19 UTC, danjov approved these changes

2024-12-16 14:25 UTC, merged