Add tvd and custom ids
swisstopo/swissgeol-boreholes-suite pull request #1769
Opened 2024-12-17 12:24 UTC by MiraGeowerkstatt

2024-12-17 13:10 UTC, Lehats approved these changes

2024-12-17 14:55 UTC, danjov requested changes
Q: Muss das Changelog nachgeführt werden oder wird der Export generell bereits erwähnt?

2024-12-17 14:55 UTC, danjov commented on src/api/Controllers/ExportController.cs
> +            .ThenInclude(bc => bc.Codelist)
PP: Das `.ThenInclude` auf der selben Zeile, wie das vorangestellte `Include` behalten. Macht es klarer, da sich `ThenInclude` auf die `BoreholeCodelists` bezieht.

2024-12-17 14:55 UTC, danjov commented on src/api/Controllers/ExportController.cs
> +                var codelistValue = (b.BoreholeCodelists ?? Enumerable.Empty<BoreholeCodelist>()).FirstOrDefault(bc => bc.CodelistId == header.CodelistId)?.Value;
REQ: Das Konstrukt `b.BoreholeCodelists ?? Enumerable.Empty<BoreholeCodelist>()`  kommt bereits auf Zeile 88 weiter oben vor. Vorschlag: In Variable auslagern.

2024-12-17 14:58 UTC, MiraGeowerkstatt commented
> Q: Muss das Changelog nachgeführt werden oder wird der Export generell bereits erwähnt?

Wir haben diesen Eintrag "Add JSON and CSV export for single and multiple boreholes." denke das ist ok, oder soll es spezifischer sein?

2024-12-18 15:04 UTC, danjov commented
> > Q: Muss das Changelog nachgeführt werden oder wird der Export generell bereits erwähnt?
> 
> Wir haben diesen Eintrag "Add JSON and CSV export for single and multiple boreholes." denke das ist ok, oder soll es spezifischer sein?

Nein, das passt gut.

2024-12-18 15:05 UTC, danjov approved these changes

2024-12-18 15:05 UTC, danjov commented on src/api/Controllers/ExportController.cs
> +            .SelectMany(b => GetBoreholeCodelists(b))
PP: _Syntactic sugar_ → Hier kann man es zu `.SelectMany(GetBoreholeCodelists)` vereinfachen.

2024-12-19 07:21 UTC, MiraGeowerkstatt commented on src/api/Controllers/ExportController.cs
> +            .SelectMany(b => GetBoreholeCodelists(b))
💡

2024-12-19 07:21 UTC, merged